### ISSUE TITLE
Error uploading sample

### ISSUE THREAD

**Issue by backinside** [mike-rankin/ESP8266_OLED_Display#3]
I've just built this, but when I try to upload the wifi scan sample, I get an error:
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

If I plug the board in, the red led lights up, and the blue led is blinking
If I push the button while plugging in, red led lights up, and the blue stays dark
So I believe the board is in programming mode, but I get the same error message in both cases
These are my board settings:
![esp](https://user-images.githubusercontent.com/454430/29482625-2f55ed26-8495-11e7-9ebb-f6a11cac32fc.png)

**Comment by mike-rankin** [comment]
It sounds like the FTDI is not communicating to the microprocessor.

**Comment by backinside** [comment]
I've just managed to get it to work, thanks :)
